services:
  - name: salvage-calc-api
    type: web
    env: python
    plan: free  # Change if you need more resources
    buildCommand: ./render-build.sh && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: "10000"
